In [1]:
import tensorflow
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D

In [2]:
model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
model.trainable = False

In [3]:
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                           

In [4]:
model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_max_pooling2d (Globa  (None, 2048)             0         
 lMaxPooling2D)                                                  
                                                                 
Total params: 23,587,712
Trainable params: 0
Non-trainable params: 23,587,712
_________________________________________________________________


In [7]:
import pickle

In [8]:
pickle.dump(model,open('model.pkl', 'wb'))

INFO:tensorflow:Assets written to: ram://b7501e6d-e7f3-45b4-aa3f-3da46b0ccea3/assets


INFO:tensorflow:Assets written to: ram://b7501e6d-e7f3-45b4-aa3f-3da46b0ccea3/assets


In [6]:
img = image.load_img('images/1163.jpg', target_size=(224,224))

In [7]:
img = image.img_to_array(img)

In [8]:
img.shape

(224, 224, 3)

convert batch

In [9]:
import numpy as np

In [10]:
img = np.expand_dims(img, axis=0)

In [11]:
img.shape

(1, 224, 224, 3)

Preprocessing

In [12]:
processed_img = preprocess_input(img)

In [13]:
img

array([[[[131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         ...,
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ]],

        [[131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         ...,
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ]],

        [[131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         ...,
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ]],

        ...,

        [[131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         [131.32   , 138.22101, 151.061  ],
         ...,


In [14]:
processed_img

array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


Predict

In [15]:
res = model.predict(processed_img)

1/1 [==============================] - 7s 7s/step


In [16]:
res.shape

(1, 2048)

## Flatten

In [17]:
res.flatten().shape

(2048,)

## Norm

In [18]:
from numpy.linalg import norm

In [19]:
model.predict(processed_img).flatten()/norm(model.predict(processed_img).flatten())

1/1 [==============================] - 0s 45ms/step


array([0.00491866, 0.05812975, 0.00543875, ..., 0.00351526, 0.05245371,
       0.03639513], dtype=float32)

# Extract feature 

In [20]:
def extract_feature(img_path,model):
    img = image.load_img(img_path, target_size=(224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img,axis=0)
    img = preprocess_input(img)
    res = model.predict(img).flatten()
    res = res/norm(res)
    
    return res

In [21]:
import os

In [22]:
filenames = []

for file in os.listdir('images'):
    filenames.append(os.path.join('images', file))

In [23]:
filenames

['images\\10000.jpg',
 'images\\10001.jpg',
 'images\\10002.jpg',
 'images\\10003.jpg',
 'images\\10004.jpg',
 'images\\10005.jpg',
 'images\\10006.jpg',
 'images\\10007.jpg',
 'images\\10008.jpg',
 'images\\10009.jpg',
 'images\\10010.jpg',
 'images\\10011.jpg',
 'images\\10012.jpg',
 'images\\10013.jpg',
 'images\\10014.jpg',
 'images\\10015.jpg',
 'images\\10016.jpg',
 'images\\10017.jpg',
 'images\\10018.jpg',
 'images\\10019.jpg',
 'images\\10020.jpg',
 'images\\10021.jpg',
 'images\\10022.jpg',
 'images\\10023.jpg',
 'images\\10024.jpg',
 'images\\10025.jpg',
 'images\\10026.jpg',
 'images\\10027.jpg',
 'images\\10028.jpg',
 'images\\10029.jpg',
 'images\\10030.jpg',
 'images\\10031.jpg',
 'images\\10032.jpg',
 'images\\10033.jpg',
 'images\\10034.jpg',
 'images\\10035.jpg',
 'images\\10037.jpg',
 'images\\10039.jpg',
 'images\\10040.jpg',
 'images\\10041.jpg',
 'images\\10042.jpg',
 'images\\10043.jpg',
 'images\\10044.jpg',
 'images\\10045.jpg',
 'images\\10046.jpg',
 'images\\

In [24]:
from tqdm import tqdm

In [25]:
feature_list = []
for file in (filenames):
    feature_list.append(extract_feature(file, model))
    

1/1 [==============================] - 0s 42ms/step


In [26]:
import pickle

In [27]:
pickle.dump(feature_list,open('feature_list.pkl', 'wb'))
pickle.dump(filenames,open('filename.pkl', 'wb'))